swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: API endpoints of transactions
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /accounts/:accountId:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: User Transactions API
      description: API for fetching all transactions list
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User transactions list retrieved successully
          schema:
            $ref: "#/definitions/TransactionsResponse"
        "401":
          description: User not authorized
        "500":
          description: Internal Server Error
    post:
      tags:
        - Transactions Module
      summary: Update Transactions API
      description: API for editing a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: body
          name: body
          description: Transaction Payload
          required: true
          schema:
            $ref: "#/definitions/AddTransactionBody"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction updated successully
        "401":
          description: User not authorized
        "500":
          description: Internal Server Error

  /accounts/:accountId/:transactionId:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: User Transactions API
      description: API for fetching all details of a transaction by its ID
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Transactions retrieved successully
          schema:
            $ref: "#/definitions/SingleTransactionResponse"
        "401":
          description: User not authorized
        "500":
          description: Internal Server Error
  /accounts/:accountId/:transactionId/edit:
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Update Transactions API
      description: API for editing a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: body
          name: body
          description: Transaction Payload
          required: true
          schema:
            $ref: "#/definitions/SingleTransactionBody"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction updated successully
          schema:
            $ref: "#/definitions/SingleTransactionResponse"
        "401":
          description: User not authorized
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  TransactionsResponse:
    type: object
    properties:
      message:
        type: string
      transactions:
        type: array
        items:
          type: object
  SingleTransactionBody:
    type: object
    properties:
      id:
        type: string
      category:
        type: string
      note:
        type: string
  SingleTransactionResponse:
    type: object
    properties:
      date:
        type: string
      description:
        type: string
      amont:
        type: string
      transaction type:
        type: string
      category:
        type: string
      notes:
        type: string

  AddTransactionBody:
    type: object
    properties:
      date:
        type: string
      description:
        type: string
      amont:
        type: string
      transaction type:
        type: string
      category:
        type: string
      notes:
        type: string
